version: "3.7"

services:
  database:
    image: postgres
    restart: always
    env_file:
      - back/.env
    ports:
      - "5432:5432"
    volumes:
      - data:/var/lib/postgresql/data

  server:
    build:
      context: .
      dockerfile: back/Dockerfile
    env_file: back/.env
    depends_on:
      - database
    networks:
      - default
    ports:
      - "8080:8080"

  frontend:
    build:
      context: ./front
      dockerfile: Dockerfile
    restart: always
    ports:
      - '8085:80'
    depends_on:
      - server
volumes:
  data:
